apiVersion: v1
kind: Namespace
metadata:
  name: pr-{{PR_ID}}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-{{PR_ID}}
  namespace: pr-{{PR_ID}}
spec:
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - name: web
        image: siddharthdoc/demo-app:{{IMAGE_TAG}}
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: svc-{{PR_ID}}
  namespace: pr-{{PR_ID}}
spec:
  selector:
    app: demo-app
  ports:
    - port: 80
      targetPort: 5000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-{{PR_ID}}
  namespace: pr-{{PR_ID}}
spec:
  rules:
  - host: pr-{{PR_ID}}.172.17.5.38.nip.io   # REPLACE YOUR_IP
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-{{PR_ID}}
            port:
              number: 80